[build]
  # Publish the src directory (where your index.html is located)
  publish = "src"
  
  # No build command needed for static HTML
  command = ""

# Specify Node.js version for compatibility
[build.environment]
  NODE_VERSION = "18.19.0"

# Disable Lighthouse plugin to avoid Node.js version conflicts
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  enabled = false

# Redirect rules for clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form submission redirects
[[redirects]]
  from = "/success"
  to = "/index.html?subscribed=true"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 